exp_group: SVAMP-Gen
run_name: svamp
dataset_name: svamp
train_bz: 16
eval_bz: 16
lr: 1.e-5
max_grad_norm: 1.0
train_steps: 25000

scheduler_type: linear
warmup_steps: 500
decay_ratio: 0.5

eval_steps:  200
max_input_len: 128
max_output_len: 64
use_actual_num: True
output_as_code: True
use_adapter: True
adapter_tuning: False
model_init_pth: Tianduo/MsAT-RoBERTaGen
patience: 35